### ISSUE TITLE
Bad interaction between quoting and joins

### ISSUE THREAD

**Issue by jrouzierinverse** [damil/SQL-Abstract-More#10]
I found an issue when using quote_char and the join spec.

```perl
use SQL::Abstract::More;
my $sqla = SQL::Abstract::More->new(quote_char => '`');
my ($sql, @bind) = $sqla->select(-from => [-join => qw(t1 =>{a=a} t2)]);

```
SQL produced
 ``` SELECT * FROM t1 LEFT OUTER JOIN t2 ON ( `t1.a` = `t2.a` ) ```
SQL expected
 ``` SELECT * FROM t1 LEFT OUTER JOIN t2 ON ( `t1`.`a` = `t2`.`a` ) ```

Do you know of any work around for this issue?

**Comment by sezal** [comment]
it might be related with https://github.com/damil/SQL-Abstract-More/pull/6
