### ISSUE TITLE
installation information in README

### ISSUE THREAD

**Issue by nunorc** [damil/SQL-Abstract-More#7]
Hello, in your README file, the set of instructions in the INSTALLATION section uses the Build.PL script, but the script available for installation seems to be Makefile.PL. It seems the README is outdated?

Thank you

**Comment by damil** [comment]
Le 28.05.2015 22:18, Nuno Carvalho a écrit :
>
> Hello, in your README file, the set of instructions in the 
> INSTALLATION section uses the Build.PL script, but the script 
> available for installation seems to be Makefile.PL. It seems the 
> README is outdated?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/damil/SQL-Abstract-More/issues/7>.
>
Thanks Nuno, you are right, this was outdated. Just fixed.

**Comment by nunorc** [comment]
Thank you.
